Repository annahxxl/check-mate, pull requests merged in 2021-09, with the labels that each got.

#4 F01 - Vue 개발환경 설정
  frontend/.browserslistrc
  frontend/.editorconfig
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/README.md
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/shims-vue.d.ts
  frontend/src/store/index.ts
  frontend/src/views/About.vue
  frontend/src/views/Home.vue
  frontend/tsconfig.json
Labels: 🤳프론트엔드

#13 B05 - 응답 포맷 세팅
  backend/src/app.module.ts
  backend/src/auth/constants.ts
  backend/src/common/http-exception.filter.ts
  backend/src/common/interceptors/success.interceptor.ts
  backend/src/common/middlewares/logger.middleware.ts
  backend/src/main.ts
Labels: 🧵백엔드

#14 B02 - Google 소셜 로그인 기능 구현
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.spec.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt/jwt.guard.ts
  backend/src/auth/jwt/jwt.payload.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/auth/passport/google.strategy.ts
  backend/src/main.ts
  backend/src/users/users.controller.spec.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.entity.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.spec.ts
  backend/src/users/users.service.ts
Labels: 🧵백엔드

#15 B04 - Github 소셜 로그인 기능 구현
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/passport/github.strategy.ts
  backend/src/auth/passport/google.strategy.ts
Labels: 🧵백엔드, 🎈기능

#19 F01 - Vue 개발환경 설정
  .idea/.gitignore
  .idea/check-mate.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  frontend/.browserslistrc
  frontend/.editorconfig
  frontend/.eslintrc.js
  frontend/README.md
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/logo.png
  frontend/src/components/HelloWorld.vue
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/shims-tsx.d.ts
  frontend/src/shims-vue.d.ts
  frontend/src/store/index.ts
  frontend/src/views/Home.vue
  frontend/tslint.json
Labels: 🤳프론트엔드

#20 U01 - Base Layout 화면 개발
  .idea/prettier.xml
  .idea/workspace.xml
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/HelloWorld.vue
  frontend/src/components/templates/BaseLayout.vue
  frontend/src/router/index.ts
  frontend/src/shims-tsx.d.ts
  frontend/src/shims-vue.d.ts
  frontend/src/store/index.ts
  frontend/tslint.json
Labels: 🎨UI

#21 F02 - Navbar 컴포넌트 개발
  frontend/src/components/UI/organisms/NavigationBar.vue
  frontend/src/components/templates/BaseLayout.vue
Labels: 🎈기능, 🤳프론트엔드

#24 B07 - Project CRUD API 개발
  backend/src/app.module.ts
  backend/src/main.ts
  backend/src/projects/dto/project.dto.ts
  backend/src/projects/projects.controller.spec.ts
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.entity.ts
  backend/src/projects/projects.module.ts
  backend/src/projects/projects.service.spec.ts
  backend/src/projects/projects.service.ts
  backend/src/users/users.entity.ts
Labels: 🧵백엔드, 🎈기능
